### ISSUE TITLE
Cover url parsing

### ISSUE THREAD

**Issue by mahburg** [darthbatman/billboard-top-100#11]
It seems to me the best way to return the url for the cover is just the url. However, the url is currently being parsed as "background-image: url(https://charts-static.billboard.com/img/2017/01/bon-jovi.jpg"

This isn't the end of the world, however, it isn't even correct in its current implementation. It doesn't have a closing parenthese for the 'url('.

**Comment by mahburg** [comment]
After a little more digging I have found that it is not doing it on all records, but is still fairly prevalent.
`{
"rank": "9",
"title": "Love You Down",
"artist": "Ready For The World",
"cover": "background-image: url(https://charts-static.billboard.com/img/1984/12/ready-for-the-world-vvi.jpg",
"position": {
"Last Week": "12",
"Peak Position": "9",
"Wks on Chart": "13"
}
},
{
"rank": "10",
"title": "Change Of Heart",
"artist": "Cyndi Lauper",
"cover": "https://charts-static.billboard.com/img/2016/12/cyndi-lauper.jpg",
"position": {
"Last Week": "3",
"Peak Position": "3",
"Wks on Chart": "13"
}
}`

**Comment by kalynbaur** [comment]
Is it printing data incorrectly to the console/is it failing to return data?

**Comment by darthbatman** [comment]
fixed
