### ISSUE TITLE
Getting list from 2 to 100

### ISSUE THREAD

**Issue by testk2018** [darthbatman/billboard-top-100#15]
I am getting list from 2nd to 100 not from 1st and I need from 1st.
Can you please help me for that.

Here is the sample code How I am using this

`
        var billboard = require("billboard-top-100").getChart;

	billboard('hot-100', function(err, songs) {

	    if (err) console.log(err);

	    res.end(JSON.stringify(songs));

	});

`

**Comment by cowboysdude** [comment]
Same issue......it's starting at #2........
