### ISSUE TITLE
Position of an album over the time on chart

### ISSUE THREAD

**Issue by bodzio166** [darthbatman/billboard-top-100#16]
Hello!

Can it do smething like mentioned in the topic? I used to use modulo.site API, but not it is deprecated. I am looking for a tool to fetch album positions every time it was on the list with dates of it.

**Comment by cowboysdude** [comment]
You mean like last week it was 3, this week it's 9?  Rankings like that?

**Comment by RonPetts100** [comment]
Hello who's this again?

**Comment by bodzio166** [comment]
More like a chart with positions week by week when a record was on the Billboard chart.

 

Week 32-2018 – position 1

Week 33-2018 – position 3

Week 34-2018 – position 20

 

(Week 35-2018 – off the list)

 

Pozdrawiam serdecznie,

 

Artur „Bodzio” Bogdański

 

www.bonjovi.pl

**Comment by RonPetts100** [comment]
Are you talking about on my website?

**Comment by RonPetts100** [comment]
Me to
What's your website

**Comment by bodzio166** [comment]
I run a music related website. I used to use http://billboard.modulo.site/ API to build a graphic chart of a music album performence over the weeks when it was on the Billboard charts. Now this API is not working and I am looking for other solution to get a nice graph with performence of an album on Billboard over time, week by week.

**Comment by cowboysdude** [comment]
Yeah you're looking for data that without some serious work isn't available.   This is a free 'module'..... If that's what you want I suggest [not being hostile here] that you do some work.  It's a lot to ask for free.  :)

**Comment by darthbatman** [comment]
There are no plans to add this functionality. However, if someone adds this functionality and makes a pull request, it can be added.
