### ISSUE TITLE
Hot 100: Top Song is not returned in array

### ISSUE THREAD

**Issue by NGuernse** [darthbatman/billboard-top-100#18]
I saw the [issue was closed](https://github.com/darthbatman/billboard-top-100/issues/15https://github.com/darthbatman/billboard-top-100/issues/15), but I am still getting songs 2->99 chart but not the top song. Here's some code that handles the hot 100 list for getting the top ranked song, haven't tested but should work for most of the other charts as well:
`// Rank 1 is a special case that isn't in the list, so grab that separately`
`    const topTrackInfo = $('.chart-number-one__details');`
`    const track = topTrackInfo.children('.chart-number-one__title').text().trim();`
`    const artist = topTrackInfo.children('.chart-number-one__artist').text().trim();`
`    const rank = 1;`

**Comment by darthbatman** [comment]
Fixed by commit fc5ef9f4b1ae54508cb6ecc53791dd0e40b22cd6
