### ISSUE TITLE
songObject.position not working?

### ISSUE THREAD

**Issue by bluetidepro** [darthbatman/billboard-top-100#20]
Thanks so much for making this! It seems like `songObject.position` isn't being returned. I see it was possible removed back in this commit: https://github.com/darthbatman/billboard-top-100/commit/b3dbd202bf5290022a649c62111be63faacd4c7c#diff-5eeab9e25ee821ebaa8cabd29b38c351

Is that a bug, or does this no longer support that `position` object being returned?

**Comment by VMehta99** [comment]
I fixed it with pull request 21 :)

**Comment by darthbatman** [comment]
fixed and merged, ill update the version and publish to npm

**Comment by darthbatman** [comment]
version 2.1.3 published to npm

**Comment by bluetidepro** [comment]
Thanks @darthbatman !
