### ISSUE TITLE
new version 2.4.0 fails reading next week's link

### ISSUE THREAD

**Issue by dulmanr** [darthbatman/billboard-top-100#24]
When trying to retrieve current week's list the there is an exception thrown trying to read next week's link.
it files on line 281:
`date: $('.dropdown__date-selector-option ')[1].children[1].attribs.href.split('/')[3]`
The link does not contain href link because there isn't one :)
The code flies with the following error:
> TypeError: Cannot read property 'split' of undefined #

**Comment by darthbatman** [comment]
fixed in 2.4.1
