### ISSUE TITLE
Fetch SSL protocol errors

### ISSUE THREAD

**Issue by kyle-richardson** [darthbatman/billboard-top-100#48]
getting the following console errors when attempting to use getChart function:

Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR
TypeError: Failed to fetch

following from network information on request:
Request URL: https://www.billboard.com:80/charts/hot-100/2021-02-04
Referrer Policy: strict-origin-when-cross-origin

Referer: https:// ***(my site)
sec-ch-ua: "Chromium";v="88", "Google Chrome";v="88", ";Not A Brand";v="99"
sec-ch-ua-mobile: ?0
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36

note: the function does work locally (https://localhost:3000) using chrome without CORS security

**Comment by darthbatman** [comment]
Closing due to fixes introduced in version 2.6.1.
