### ISSUE TITLE
sometimes rank value is incorrect (shifted)

### ISSUE THREAD

**Issue by adjorno** [darthbatman/billboard-top-100#5]
Hot 100 Chart
"1961-09-16" : after rank 64
"1961-09-23": after rank 45
"1961-09-23": after rank 40 
etc.

**Comment by darthbatman** [comment]
The rank shift was occurring due to missing songs in some of the Billboard charts. The rank values should now be correct. Also, just curious, what project are you working on and how are you using billboard-top-100?

**Comment by adjorno** [comment]
I want to gather as much charts as I can to analyze it and get answer on questions like:
- What are the most popular songs for all the time?
- What did people like to listen to during some range of time? Lets say during 2004.
- Are there some cool tracks from non-popular artists which I would not face manually?

I like to listen music but now I don't have a time (job, wife, kids, home stuff) to find a new artist in regular way. That is why I want to make some tool to help me. First results are great for me. Thanks to you, your script saved a lot of time.
