### ISSUE TITLE
Api is dead

### ISSUE THREAD

**Issue by kylerchin** [darthbatman/billboard-top-100#56]
Everything returns a blank response.

**Comment by ReverseControl** [comment]
@kylerchin Could you elaborate? Details of your system, version you are running, commands you are running, responses, etc.

**Comment by kyle-richardson** [comment]
Also not working for me, `getChart` returns `null`.

Here is simplified version of my code using it, which used to work a few months ago:

```
import { getChart } from 'billboard-top-100'
...
server.get('/chart/:date', (req, res) => {
    const { date } = req.params; // date format: 'YYYY-MM-DD'
    getChart('hot-100', date, (err, chart) => {
        console.log(chart) // this returns 'null' now
        if (err) res.json({ songs: [], error: err })
        else res.json(chart)
    })
})
```

**Comment by darthbatman** [comment]
As of version 2.6.1, `getChart` and `listCharts` are working as intended.
