### ISSUE TITLE
can't parse artist-100

### ISSUE THREAD

**Issue by fbegue** [darthbatman/billboard-top-100#63]
First off - love you. Scraping is a pain, but this is so valuable.  If you need help maintaining this, I'd be glad to offer assistance.
And you should be a tip jar at the bottom of the README so I can buy you a coffee 😀

But currently seems like artist-100 isn't able to be parsed, as I throw an uncaughtException at the following line:
 `const d = moment(new Date($('.chart-results')` ...
 
For clarity, here's the exact  requestURL: ` http://www.billboard.com/charts/artist-100/`

This happening for you as well? Thanks

**Comment by darthbatman** [comment]
Hi @fbegue. Thank you for using `billboard-top-100` and thanks for flagging this bug. I have fixed this bug in #64. 
As of version 2.6.3, `getChart` is working for the "artist-100" chart as intended.
